"""Error code definitions.

Reference: Pro_Edition_Tech_Design_Phase0.md §11 Error Code Definitions
"""

from __future__ import annotations

# ── Authentication (401) ──
JWT_INVALID = "JWT_INVALID"
JWT_EXPIRED = "JWT_EXPIRED"
JWT_REVOKED = "JWT_REVOKED"
JWT_MISSING = "JWT_MISSING"
API_KEY_INVALID = "API_KEY_INVALID"

# ── Authorization (403) ──
LICENSE_INACTIVE = "LICENSE_INACTIVE"
LICENSE_EXPIRED = "LICENSE_EXPIRED"
LICENSE_CANCELLED = "LICENSE_CANCELLED"
LICENSE_SUSPENDED = "LICENSE_SUSPENDED"
DEVICE_FINGERPRINT_MISMATCH = "DEVICE_FINGERPRINT_MISMATCH"
DEVICE_LIMIT_EXCEEDED = "DEVICE_LIMIT_EXCEEDED"
PERMISSION_DENIED = "PERMISSION_DENIED"

# ── Quota (402) ──
QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
ASR_QUOTA_EXCEEDED = "ASR_QUOTA_EXCEEDED"
TTS_QUOTA_EXCEEDED = "TTS_QUOTA_EXCEEDED"
OCR_QUOTA_EXCEEDED = "OCR_QUOTA_EXCEEDED"

# ── Rate limit (429) ──
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"

# ── Key pool (503) ──
NO_AVAILABLE_KEY = "NO_AVAILABLE_KEY"
ALL_KEYS_CIRCUIT_OPEN = "ALL_KEYS_CIRCUIT_OPEN"

# ── Upstream (502/504) ──
UPSTREAM_ERROR = "UPSTREAM_ERROR"
UPSTREAM_TIMEOUT = "UPSTREAM_TIMEOUT"
UPSTREAM_NETWORK_ERROR = "UPSTREAM_NETWORK_ERROR"

# ── Validation (400) ──
VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_LICENSE_KEY_FORMAT = "INVALID_LICENSE_KEY_FORMAT"
INVALID_DEVICE_FINGERPRINT = "INVALID_DEVICE_FINGERPRINT"
INVALID_AUDIO_FORMAT = "INVALID_AUDIO_FORMAT"
AUDIO_TOO_LARGE = "AUDIO_TOO_LARGE"
INVALID_IMAGE_FORMAT = "INVALID_IMAGE_FORMAT"
IMAGE_TOO_LARGE = "IMAGE_TOO_LARGE"
TEXT_TOO_LONG = "TEXT_TOO_LONG"

# ── Not found (404) ──
LICENSE_NOT_FOUND = "LICENSE_NOT_FOUND"
ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"

# ── Conflict (409) ──
LICENSE_ALREADY_ACTIVATED = "LICENSE_ALREADY_ACTIVATED"

# ── Gateway internal (500) ──
GATEWAY_INTERNAL_ERROR = "GATEWAY_INTERNAL_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
REDIS_ERROR = "REDIS_ERROR"

# ── Gateway unavailable (503) ──
GATEWAY_UNHEALTHY = "GATEWAY_UNHEALTHY"
