"""initial_schema

Revision ID: 4a1cfeaf1eb1
Revises: 
Create Date: 2026-06-04 20:12:57.794915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1cfeaf1eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pipeline', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("event_type IN ('card_save', 'meeting', 'call', 'manual')", name='event_type_check'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='event_status_check'),
    sa.CheckConstraint('length(raw_text) <= 512000', name='raw_text_size_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_user_status', 'events', ['user_id', 'status'], unique=False)
    op.create_index('idx_events_user_type_time', 'events', ['user_id', 'event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('source_event_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("entity_type IN ('person', 'organization', 'topic', 'technology', 'project')", name='entity_type_check'),
    sa.CheckConstraint("status IN ('provisional', 'confirmed', 'merged', 'deleted')", name='entity_status_check'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='confidence_range_check'),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_canonical', 'entities', ['user_id', 'canonical_name'], unique=False)
    op.create_index('idx_entities_status', 'entities', ['user_id', 'status'], unique=False)
    op.create_index('idx_entities_user_name', 'entities', ['user_id', 'name'], unique=False)
    op.create_index('idx_entities_user_type', 'entities', ['user_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    op.create_table('associations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('association_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('source_event_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.CheckConstraint("association_type IN (\n                'alumni', 'ex_colleague', 'same_city', 'competitor',\n                'tech_overlap', 'deal_link', 'risk_link', 'supply_chain',\n                'co_occurrence'\n            )", name='association_type_check'),
    sa.CheckConstraint("status IN ('provisional', 'confirmed', 'rejected')", name='association_status_check'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='confidence_range_check'),
    sa.CheckConstraint('source_entity_id != target_entity_id', name='no_self_association_check'),
    sa.CheckConstraint('strength >= 0.0 AND strength <= 1.0', name='strength_range_check'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'association_type', name='uq_association_source_target_type')
    )
    op.create_index('idx_associations_source', 'associations', ['source_entity_id'], unique=False)
    op.create_index('idx_associations_strength', 'associations', ['user_id', 'strength'], unique=False)
    op.create_index('idx_associations_target', 'associations', ['target_entity_id'], unique=False)
    op.create_index('idx_associations_user_type', 'associations', ['user_id', 'association_type'], unique=False)
    op.create_index(op.f('ix_associations_association_type'), 'associations', ['association_type'], unique=False)
    op.create_index(op.f('ix_associations_user_id'), 'associations', ['user_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('todo_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('related_association_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_at', sa.DateTime(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('source_event_id', sa.String(length=36), nullable=False),
    sa.Column('feedback', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'done', 'dismissed', 'snoozed')", name='todo_status_check'),
    sa.CheckConstraint("todo_type IN (\n                'promise', 'help', 'care', 'followup', 'cooperation_signal', 'risk'\n            )", name='todo_type_check'),
    sa.CheckConstraint('feedback IS NULL OR length(feedback) > 0', name='feedback_check'),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='priority_range_check'),
    sa.ForeignKeyConstraint(['related_association_id'], ['associations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_todos_user_due', 'todos', ['user_id', 'due_date'], unique=False)
    op.create_index('idx_todos_user_priority', 'todos', ['user_id', 'priority', 'status'], unique=False)
    op.create_index('idx_todos_user_type_status', 'todos', ['user_id', 'todo_type', 'status'], unique=False)
    op.create_index(op.f('ix_todos_due_date'), 'todos', ['due_date'], unique=False)
    op.create_index(op.f('ix_todos_status'), 'todos', ['status'], unique=False)
    op.create_index(op.f('ix_todos_todo_type'), 'todos', ['todo_type'], unique=False)
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.create_table('snooze_schedules',
    sa.Column('todo_id', sa.String(length=36), nullable=False),
    sa.Column('original_status', sa.String(length=15), nullable=False),
    sa.Column('recover_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("original_status IN ('pending', 'in_progress')", name='original_status_check'),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_index('idx_snooze_recover_at', 'snooze_schedules', ['recover_at'], unique=False)
    op.create_index(op.f('ix_snooze_schedules_recover_at'), 'snooze_schedules', ['recover_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snooze_schedules_recover_at'), table_name='snooze_schedules')
    op.drop_index('idx_snooze_recover_at', table_name='snooze_schedules')
    op.drop_table('snooze_schedules')
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_todo_type'), table_name='todos')
    op.drop_index(op.f('ix_todos_status'), table_name='todos')
    op.drop_index(op.f('ix_todos_due_date'), table_name='todos')
    op.drop_index('idx_todos_user_type_status', table_name='todos')
    op.drop_index('idx_todos_user_priority', table_name='todos')
    op.drop_index('idx_todos_user_due', table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_associations_user_id'), table_name='associations')
    op.drop_index(op.f('ix_associations_association_type'), table_name='associations')
    op.drop_index('idx_associations_user_type', table_name='associations')
    op.drop_index('idx_associations_target', table_name='associations')
    op.drop_index('idx_associations_strength', table_name='associations')
    op.drop_index('idx_associations_source', table_name='associations')
    op.drop_table('associations')
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index('idx_entities_user_type', table_name='entities')
    op.drop_index('idx_entities_user_name', table_name='entities')
    op.drop_index('idx_entities_status', table_name='entities')
    op.drop_index('idx_entities_canonical', table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index('idx_events_user_type_time', table_name='events')
    op.drop_index('idx_events_user_status', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
