export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/input/index',
    'pages/events/index',
    'pages/events/detail',
    'pages/todos/index',
    'pages/todos/detail',
    'pages/entities/index',
    'pages/entities/detail',
    'pages/promises/index',
    'pages/promises/detail',
    'pages/reminders/index',
    'pages/mine/index',
  ],
  tabBar: {
    color: '#8a8a8a',
    selectedColor: '#A0B0C4',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'icons/home.png',
        selectedIconPath: 'icons/home-active.png',
      },
      {
        pagePath: 'pages/events/index',
        text: '事件',
        iconPath: 'icons/events.png',
        selectedIconPath: 'icons/events-active.png',
      },
      {
        pagePath: 'pages/entities/index',
        text: '人脉',
        iconPath: 'icons/people.png',
        selectedIconPath: 'icons/people-active.png',
      },
      {
        pagePath: 'pages/todos/index',
        text: '待办',
        iconPath: 'icons/todo.png',
        selectedIconPath: 'icons/todo-active.png',
      },
      {
        pagePath: 'pages/promises/index',
        text: '承诺',
        iconPath: 'icons/promise.png',
        selectedIconPath: 'icons/promise-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#A0B0C4',
    navigationBarTitleText: 'PromiseLink 基础版',
    navigationBarTextStyle: 'white',
  },
})
