"""Sprint 0: F-50 voice_sessions/turns/analytics tables

Revision ID: 538083639032
Revises: 4ff9b21a03b0
Create Date: 2026-06-05 14:41:29.346423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538083639032'
down_revision: Union[str, Sequence[str], None] = '4ff9b21a03b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('person_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_stage', sa.String(length=30), nullable=False),
    sa.Column('brief_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("relationship_stage IN (\n                'new_connection', 'understanding_needs', 'value_response',\n                'deep_trust', 'active_cooperation', 'long_term_partner', 'dormant'\n            )", name='relationship_stage_check'),
    sa.CheckConstraint('version >= 1', name='brief_version_check'),
    sa.ForeignKeyConstraint(['person_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_briefs_user_person', 'relationship_briefs', ['user_id', 'person_entity_id'], unique=True)
    op.create_index('idx_briefs_user_stage', 'relationship_briefs', ['user_id', 'relationship_stage'], unique=False)
    op.create_index(op.f('ix_relationship_briefs_person_entity_id'), 'relationship_briefs', ['person_entity_id'], unique=False)
    op.create_index(op.f('ix_relationship_briefs_relationship_stage'), 'relationship_briefs', ['relationship_stage'], unique=False)
    op.create_index(op.f('ix_relationship_briefs_user_id'), 'relationship_briefs', ['user_id'], unique=False)
    op.add_column('events', sa.Column('input_scope', sa.String(length=30), nullable=True))
    op.add_column('events', sa.Column('input_scope_confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_events_input_scope'), 'events', ['input_scope'], unique=False)
    op.add_column('todos', sa.Column('action_type', sa.String(length=30), nullable=True))
    op.add_column('todos', sa.Column('promisor_id', sa.String(length=36), nullable=True))
    op.add_column('todos', sa.Column('beneficiary_id', sa.String(length=36), nullable=True))
    op.add_column('todos', sa.Column('confirmation_status', sa.String(length=20), nullable=True))
    op.add_column('todos', sa.Column('evidence_quote', sa.Text(), nullable=True))
    op.add_column('todos', sa.Column('evidence_event_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_todos_action_type'), 'todos', ['action_type'], unique=False)
    op.create_foreign_key(None, 'todos', 'entities', ['beneficiary_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'todos', 'entities', ['promisor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_action_type'), table_name='todos')
    op.drop_column('todos', 'evidence_event_id')
    op.drop_column('todos', 'evidence_quote')
    op.drop_column('todos', 'confirmation_status')
    op.drop_column('todos', 'beneficiary_id')
    op.drop_column('todos', 'promisor_id')
    op.drop_column('todos', 'action_type')
    op.drop_index(op.f('ix_events_input_scope'), table_name='events')
    op.drop_column('events', 'input_scope_confidence')
    op.drop_column('events', 'input_scope')
    op.drop_index(op.f('ix_relationship_briefs_user_id'), table_name='relationship_briefs')
    op.drop_index(op.f('ix_relationship_briefs_relationship_stage'), table_name='relationship_briefs')
    op.drop_index(op.f('ix_relationship_briefs_person_entity_id'), table_name='relationship_briefs')
    op.drop_index('idx_briefs_user_stage', table_name='relationship_briefs')
    op.drop_index('idx_briefs_user_person', table_name='relationship_briefs')
    op.drop_table('relationship_briefs')
    # ### end Alembic commands ###
